name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm install
    - name: Create uberjar
      run: lein with-profile prod uberjar
    - name: Upload uberjar artifact
      uses: actions/upload-artifact@v1
      with:
        name: riemann-console
        path: target/riemann-console.jar
